### DISCUSSION TITLE
포스팅된 글 밑에 있는 블로그 소개 글이 중복되어 있는데 회색 부분을 제거할 수 있는 방법 알 수 있을까요?

### DISCUSSION THREAD

**Discussion by dawncoding** [pronist/hELLO#226] [Q&A] [answered]
안녕하세요. hello 티스토리 스킨 잘 사용하고 있습니다.
<img width="1122" alt="스크린샷 2024-05-01 오후 8 26 08" src="https://github.com/pronist/hello/assets/79133028/297f3f2a-252c-40c9-9497-91acee0ed7f0">
첨부한 사진과 같이 포스팅된 글 밑으로 가 보면 블로그를 소개하는 부분이 중복되어 나오는데 회색 부분을 제거할 수 있는 방법을 알 수 있을까요?

**Comment by pronist** [comment, marked as answer]
안녕하세요. 먼저 알아두실 사항입니다.

1. 회색 부분은 스킨에서 자체적으로 제공하는 기능 입니다. (다크모드 지원)
2. 흰색 부분은 티스토리에서 추가한 `Namecard` 기능입니다. (다크모드 미지원)

사용하고 계시는 스킨 버전이 v4.2.0 로 파악됩니다. 티스토리에서 추가한 기능은 다크모드 미지원으로 이후 버전부터 스킨에서 자체적으로 출력을 하지 않도록 설정되어 있습니다. 하지만, 질문 주신대로 회색은 지우고 흰색 부분만 남기고 싶으시다면 버전을 v4.4.0 으로 업데이트 한 뒤 다음과 같은 코드를 입력해보시기 바랍니다.

```css
#post #footer #author {
    display: none
}
```

추가적으로 `Namecard` 를 비활성화 시키는 코드는 지워야합니다. `style.css` 에서 다음과 같은 코드를 지워주세요.

```css
div[data-tistory-react-app="Namecard"] {
  display: none
}
```
