### DISCUSSION TITLE
사이드 메뉴에서 나오는 분류전체보기 메뉴를 사라지게 할 수 없을까요?

### DISCUSSION THREAD

**Discussion by theCyrano** [pronist/hELLO#237] [Q&A] [answered]
제목과 같이 전체보기 메뉴를 제외하고 설정해둔 카테고리로만으로 메뉴를 구성하고 싶은데요.. 수정할 수 있는 방법이 있을까요?

**Comment by pronist** [comment, marked as answer]
@theCyrano 안녕하세요.

**style.css** 에 다음과 같은 코드를 입력해보시기 바랍니다.

```css
#category > .tt_category > li > .link_tit {
  display:none;
}
```
