### DISCUSSION TITLE
티스토리 스킨 글 내용 ul에 들여쓰기 추가

### DISCUSSION THREAD

**Discussion by timothy-jeong** [pronist/hELLO#275] [Ideas]
안녕하세요, 티스토리에서 만들어주신 hello 스킨을 적용중인 사람입니다.

현재 4.10.1 를 적용중인데, 글 내용에 포함되는 목록(ui)이 글을 쓰는 시점인 편집기 화면에서는 들여쓰기가 된 상태로 보이지만, 실제 글을 발행했을때는 들여쓰기가 되지 않은 상태로 보여지는 현상을 자체 수정하여 사용중입니다.

hello 스킨을 이용중인 분들 중에 저와 같은 경험을 하신분들이 있을것 같아서 다음과 같은 css 요소 추가를 제안드립니다.

```css
/* 글 내용에 포함된 ul의 들여쓰기 적용 */
ul[data-ke-list-type="disc"] {
  list-style-type: disc;
  padding-left: 1.5rem;
}

ol[data-ke-list-type="decimal"] {
  list-style-type: decimal;
  padding-left: 1.5rem;
}
```
